services:
  frontend:
    build:
      context: client
    ports:
      - 4000:4000
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    environment:
    - VITE_PROPERTIES_API_URL=localhost
    - VITE_PROPERTIES_API_PORT=4001
    depends_on:
      - backend

  backend:
    build:
      context: server
    ports:
      - 4001:4001
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: always